import type { ProjectTemplate } from './types';

export const DEFAULT_TEMPLATES: ProjectTemplate[] = [
  {
    id: 'blank',
    name: 'Blank Project',
    description: 'Start with an empty canvas',
    category: 'Basic',
    thumbnail: '/templates/blank.svg',
    initialNodes: [],
    initialEdges: [],
    settings: {},
  },
  {
    id: 'calculator',
    name: 'Simple Calculator',
    description: 'Basic arithmetic operations',
    category: 'Examples',
    thumbnail: '/templates/calculator.svg',
    initialNodes: [
      {
        id: 'input-a',
        type: 'input-node',
        position: { x: 100, y: 100 },
        data: { label: 'Input A', value: 0, type: 'number' },
      },
      {
        id: 'input-b',
        type: 'input-node',
        position: { x: 100, y: 200 },
        data: { label: 'Input B', value: 0, type: 'number' },
      },
      {
        id: 'add',
        type: 'plus-node',
        position: { x: 300, y: 150 },
        data: { label: 'Add' },
      },
      {
        id: 'output',
        type: 'output-node',
        position: { x: 500, y: 150 },
        data: { label: 'Result' },
      },
    ],
    initialEdges: [
      {
        id: 'input-a-to-add',
        source: 'input-a',
        target: 'add',
        sourceHandle: 'output',
        targetHandle: 'a',
      },
      {
        id: 'input-b-to-add',
        source: 'input-b',
        target: 'add',
        sourceHandle: 'output',
        targetHandle: 'b',
      },
      {
        id: 'add-to-output',
        source: 'add',
        target: 'output',
        sourceHandle: 'output',
        targetHandle: 'input',
      },
    ],
    settings: {},
  },
  {
    id: 'boolean-logic',
    name: 'Boolean Logic Gates',
    description: 'AND, OR, NOT gates example',
    category: 'Examples',
    thumbnail: '/templates/boolean.svg',
    initialNodes: [
      {
        id: 'bool-a',
        type: 'input-node',
        position: { x: 50, y: 100 },
        data: { label: 'A', value: true, type: 'boolean' },
      },
      {
        id: 'bool-b',
        type: 'input-node',
        position: { x: 50, y: 200 },
        data: { label: 'B', value: false, type: 'boolean' },
      },
      {
        id: 'and-gate',
        type: 'and-node',
        position: { x: 250, y: 100 },
        data: { label: 'AND' },
      },
      {
        id: 'or-gate',
        type: 'or-node',
        position: { x: 250, y: 200 },
        data: { label: 'OR' },
      },
      {
        id: 'output-and',
        type: 'output-node',
        position: { x: 450, y: 100 },
        data: { label: 'AND Result' },
      },
      {
        id: 'output-or',
        type: 'output-node',
        position: { x: 450, y: 200 },
        data: { label: 'OR Result' },
      },
    ],
    initialEdges: [
      {
        id: 'a-to-and',
        source: 'bool-a',
        target: 'and-gate',
        sourceHandle: 'output',
        targetHandle: 'a',
      },
      {
        id: 'b-to-and',
        source: 'bool-b',
        target: 'and-gate',
        sourceHandle: 'output',
        targetHandle: 'b',
      },
      {
        id: 'a-to-or',
        source: 'bool-a',
        target: 'or-gate',
        sourceHandle: 'output',
        targetHandle: 'a',
      },
      {
        id: 'b-to-or',
        source: 'bool-b',
        target: 'or-gate',
        sourceHandle: 'output',
        targetHandle: 'b',
      },
      {
        id: 'and-to-output',
        source: 'and-gate',
        target: 'output-and',
        sourceHandle: 'output',
        targetHandle: 'input',
      },
      {
        id: 'or-to-output',
        source: 'or-gate',
        target: 'output-or',
        sourceHandle: 'output',
        targetHandle: 'input',
      },
    ],
    settings: {},
  },
];
