import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { LayoutMenu } from "@/components/layout/layout-menu";
import { ProjectManagerProvider } from "@/lib/context/project-manager.context";
import { AppErrorBoundary } from "@/components/error-boundary/error-boundary";
import { GlobalErrorMonitor } from "@/components/error-boundary/global-error-monitor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased relative`}>
          <AppErrorBoundary>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <ProjectManagerProvider>
                <LayoutMenu />
                <div className="h-full w-full flex flex-col items-center justify-center">
                  {children}
                </div>
                <Toaster />
                <GlobalErrorMonitor />
              </ProjectManagerProvider>
            </ThemeProvider>
          </AppErrorBoundary>
        </body>
      </html>
    </>
  )
}
